name: reallyseth
favicon: null
layout_spectrum: 0.9675193771254271
typography_spectrum: 0.40412174887023866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4374472494237125
  lightness: 0.13571439357474446
  saturation: 0.0017574080266058445
  rhythmicContrast: 0.6756888183299452
purpose: []
