typography_spectrum: 0.4041217488702387
color:
  saturation: 0.001757408026605844
  brandStrength: 0.4374472494237125
  rhythmicContrast: 0.6756888183299452
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  lightness: 0.1357143935747445
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9675193771254271
analytics:
  twitter: null
  google: null
  facebook: null
name: reallyseth
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Headline
purpose: []
